spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springCloud?createDatabaseIfNotExist=true
    username: root
    password: Hoang01693113424
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

